# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\tmpcprompt\"g\n\x10RegisterPartyReq\x12\x10\n\x08party_id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x19\n\x11\x61ttestation_quote\x18\x03 \x01(\x0c\x12\x18\n\x10\x61ttestation_kind\x18\x04 \x01(\t\"&\n\x0bRegisterAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"L\n\x10\x43reateSessionReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x10\n\x08mpc_ring\x18\x03 \x01(\t\"%\n\nSessionAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"M\n\x0fSubmitPromptReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0bowner_party\x18\x02 \x01(\t\x12\x11\n\ttoken_ids\x18\x03 \x03(\r\"*\n\x0fSubmitPromptAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"K\n\x0fRunInferenceReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\r\x12\x0c\n\x04topk\x18\x03 \x01(\r\"\'\n\x05Token\x12\x10\n\x08token_id\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\",\n\nStepTiming\x12\x12\n\nstep_index\x18\x01 \x01(\r\x12\n\n\x02ms\x18\x02 \x01(\x02\"b\n\x0eInferenceEvent\x12!\n\x05token\x18\x01 \x01(\x0b\x32\x10.mpcprompt.TokenH\x00\x12\'\n\x06timing\x18\x02 \x01(\x0b\x32\x15.mpcprompt.StepTimingH\x00\x42\x04\n\x02\x65v\"C\n\x07Metrics\x12\x19\n\x11tokens_per_second\x18\x01 \x01(\x01\x12\x1d\n\x15triple_pool_remaining\x18\x02 \x01(\r\"\x07\n\x05\x45mpty2\xdf\x02\n\x0b\x43oordinator\x12\x44\n\rRegisterParty\x12\x1b.mpcprompt.RegisterPartyReq\x1a\x16.mpcprompt.RegisterAck\x12\x43\n\rCreateSession\x12\x1b.mpcprompt.CreateSessionReq\x1a\x15.mpcprompt.SessionAck\x12\x46\n\x0cSubmitPrompt\x12\x1a.mpcprompt.SubmitPromptReq\x1a\x1a.mpcprompt.SubmitPromptAck\x12G\n\x0cRunInference\x12\x1a.mpcprompt.RunInferenceReq\x1a\x19.mpcprompt.InferenceEvent0\x01\x12\x34\n\x0c\x46\x65tchMetrics\x12\x10.mpcprompt.Empty\x1a\x12.mpcprompt.Metricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERPARTYREQ']._serialized_start=32
  _globals['_REGISTERPARTYREQ']._serialized_end=135
  _globals['_REGISTERACK']._serialized_start=137
  _globals['_REGISTERACK']._serialized_end=175
  _globals['_CREATESESSIONREQ']._serialized_start=177
  _globals['_CREATESESSIONREQ']._serialized_end=253
  _globals['_SESSIONACK']._serialized_start=255
  _globals['_SESSIONACK']._serialized_end=292
  _globals['_SUBMITPROMPTREQ']._serialized_start=294
  _globals['_SUBMITPROMPTREQ']._serialized_end=371
  _globals['_SUBMITPROMPTACK']._serialized_start=373
  _globals['_SUBMITPROMPTACK']._serialized_end=415
  _globals['_RUNINFERENCEREQ']._serialized_start=417
  _globals['_RUNINFERENCEREQ']._serialized_end=492
  _globals['_TOKEN']._serialized_start=494
  _globals['_TOKEN']._serialized_end=533
  _globals['_STEPTIMING']._serialized_start=535
  _globals['_STEPTIMING']._serialized_end=579
  _globals['_INFERENCEEVENT']._serialized_start=581
  _globals['_INFERENCEEVENT']._serialized_end=679
  _globals['_METRICS']._serialized_start=681
  _globals['_METRICS']._serialized_end=748
  _globals['_EMPTY']._serialized_start=750
  _globals['_EMPTY']._serialized_end=757
  _globals['_COORDINATOR']._serialized_start=760
  _globals['_COORDINATOR']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
