# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterParty = channel.unary_unary(
                '/mpcprompt.Coordinator/RegisterParty',
                request_serializer=coordinator__pb2.RegisterPartyReq.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/mpcprompt.Coordinator/CreateSession',
                request_serializer=coordinator__pb2.CreateSessionReq.SerializeToString,
                response_deserializer=coordinator__pb2.SessionAck.FromString,
                _registered_method=True)
        self.SubmitPrompt = channel.unary_unary(
                '/mpcprompt.Coordinator/SubmitPrompt',
                request_serializer=coordinator__pb2.SubmitPromptReq.SerializeToString,
                response_deserializer=coordinator__pb2.SubmitPromptAck.FromString,
                _registered_method=True)
        self.RunInference = channel.unary_stream(
                '/mpcprompt.Coordinator/RunInference',
                request_serializer=coordinator__pb2.RunInferenceReq.SerializeToString,
                response_deserializer=coordinator__pb2.InferenceEvent.FromString,
                _registered_method=True)
        self.FetchMetrics = channel.unary_unary(
                '/mpcprompt.Coordinator/FetchMetrics',
                request_serializer=coordinator__pb2.Empty.SerializeToString,
                response_deserializer=coordinator__pb2.Metrics.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterParty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterParty': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterParty,
                    request_deserializer=coordinator__pb2.RegisterPartyReq.FromString,
                    response_serializer=coordinator__pb2.RegisterAck.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=coordinator__pb2.CreateSessionReq.FromString,
                    response_serializer=coordinator__pb2.SessionAck.SerializeToString,
            ),
            'SubmitPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPrompt,
                    request_deserializer=coordinator__pb2.SubmitPromptReq.FromString,
                    response_serializer=coordinator__pb2.SubmitPromptAck.SerializeToString,
            ),
            'RunInference': grpc.unary_stream_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=coordinator__pb2.RunInferenceReq.FromString,
                    response_serializer=coordinator__pb2.InferenceEvent.SerializeToString,
            ),
            'FetchMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMetrics,
                    request_deserializer=coordinator__pb2.Empty.FromString,
                    response_serializer=coordinator__pb2.Metrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpcprompt.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mpcprompt.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpcprompt.Coordinator/RegisterParty',
            coordinator__pb2.RegisterPartyReq.SerializeToString,
            coordinator__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpcprompt.Coordinator/CreateSession',
            coordinator__pb2.CreateSessionReq.SerializeToString,
            coordinator__pb2.SessionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpcprompt.Coordinator/SubmitPrompt',
            coordinator__pb2.SubmitPromptReq.SerializeToString,
            coordinator__pb2.SubmitPromptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mpcprompt.Coordinator/RunInference',
            coordinator__pb2.RunInferenceReq.SerializeToString,
            coordinator__pb2.InferenceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpcprompt.Coordinator/FetchMetrics',
            coordinator__pb2.Empty.SerializeToString,
            coordinator__pb2.Metrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
